l_english:
 MESSAGE_SETTINGS_WINDOW_NAME: "Message Settings"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nEdit Message frequency and visibility by filtered groups."
 MESSAGE_SETTINGS_WINDOW_RESET: "Reset to Default"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Reset Message Settings#!\n#I Click to reset current changes to Default Settings#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Apply Changes"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Click to close the Message Settings window and save current changes#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Feed"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Never"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Filter Group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Name of the message filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Appearance"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "How to display messages of this filter group"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "If game should pause when messages of this filter appear"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Toggle Auto-Pause#!\n#I Toggle to pause the game when messages of this filter appear#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Dismiss Message#!\n#I Click to dismiss the current message and show the next message in the queue#!"
